accounts/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='accounts_index'),
    path('login/', login_view, name='accounts_login'),
    path('logout/', logout_view, name='accounts_logout'),
    path('user_signup/', user_signup, name='accounts_user_signup'),
    path('admininstration/accounts/signup/', common_reg, name='accounts_admin_accounts'),
]

agro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('user/', include('user.urls')),
    path('lab/', include('lab.urls')),
    path('officer/', include('officer.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='lab_index'),
    path('appointments/', appointments, name='lab_appointments'),
    path('confirm_appointment/<int:id>/', confirm_appointment, name='lab_confirm_appointment'),
    path('cancel_appointment/<int:id>/', cancel_appointment, name='lab_cancel_appointment'),
    path('appointment_list/', appointment_list, name='lab_appointment_list'),
    path('result/<int:id>/', lab_result, name='lab_result'),
    path('result_details/<int:id>/', result_details, name='lab_result_details'),
    path('user_query/', user_query_list, name='lab_user_query'),
    path('user_query/<int:pk>/', user_query_detail, name='lab_user_query_detail'),
    path('query_reply/<int:pk>/', query_reply, name='lab_query_reply'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password

# Create your models here.


def phone_validator(value):
    if value.isdigit() and len(value) == 10:
        return value
    else:
        raise ValidationError('Phone number must be of 10 digits')

def aadhar_validator(value):
    if value.isdigit() and len(value) == 12:
        return value
    else:
        raise ValidationError('Aadhar number must be of 12 digits')

class User(AbstractUser):
    user_id = models.BigAutoField(primary_key=True)
    phone = models.CharField(max_length=10, validators=[phone_validator], unique=True)
    aadhar = models.ImageField(upload_to='aadhar')
    address = models.TextField(max_length=100)
    user_type = models.CharField(max_length=10, default='officer')
    password = models.CharField(max_length=100, validators=[validate_password])
    def __str__(self):
        return self.username

class Lab(models.Model):
    lab_id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=100)
    address = models.TextField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=10, validators=[phone_validator], unique=True)
    registration_number = models.CharField(max_length=10)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

lab/models.py
from django.db import models
from user.models import LabAppointment

# Create your models here.

class LabResult(models.Model):
    lab_res_id = models.BigAutoField(primary_key=True)
    lab_appointment = models.ForeignKey(LabAppointment, on_delete=models.CASCADE)
    result = models.TextField(max_length=1000, verbose_name="Result Description")
    file = models.FileField(upload_to='lab_result', verbose_name="File", null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.result

accounts/forms.py
from django import forms
from .models import User, Lab

class CommonForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput(), label='Confirm Password')
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone', 'aadhar', 'address', 'username', 'password']

    def clean(self):
        cleaned_data = super(CommonForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )


class LabExtraForm(forms.ModelForm):
    """Form definition for LabExtra."""

    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput(), label='Confirm Password')
    class Meta:
        """Meta definition for LabExtraform."""

        model = User
        fields = ('username', 'password')

    def clean(self):
        cleaned_data = super(LabExtraForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )

class LabForm(forms.ModelForm):
    """Form definition for Lab."""

    class Meta:
        """Meta definition for Labform."""

        model = Lab
        exclude = ('owner',)


class CForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput(), label='Confirm Password')
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone', 'username', 'password']

    def clean(self):
        cleaned_data = super(CForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from .forms import CommonForm, LabForm, LabExtraForm, CForm
from django.contrib import messages
from officer.models import Scheme

# Create your views here.

def index(request):
    context = {}
    context['schemes'] = Scheme.objects.all()[::-1]
    return render(request, 'accounts/index.html', context)

#login
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            if user.user_type == 'officer':
                return redirect('/officer/')
            elif user.user_type == 'lab':
                return redirect('/lab/')
            elif user.user_type == 'user':
                return redirect('user_index')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

#logout
def logout_view(request):
    logout(request)
    return redirect('accounts_login')

#user signup
def user_signup(request):
    if request.method == 'POST':
        form = CommonForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.set_password(form.cleaned_data.get('password'))
            obj.user_type = 'user'
            obj.save()
            messages.success(request, 'Account successfully created!')
            return redirect('accounts_login')
    else:
        form = CommonForm()
    return render(request, 'accounts/user_signup.html', {'form': form})

def common_reg(request):
    if request.method == 'GET':
        form = CForm()
        context = {'form': form}
        return render(request, 'accounts/common.html', context)
    elif request.method == 'POST':
        form = CForm(request.POST)
        if form.is_valid():
            obj1 = form.save(commit=False)
            obj1.set_password(form.cleaned_data['password'])
            obj1.user_type = request.POST['user_type']
            obj1.aadhar = 'None'
            obj1.address = 'None'
            obj1.save()
            messages.success(request, 'Account successfully created!')
            return redirect('accounts_login')
        else:
            context = {'form': form}
            return render(request, 'accounts/common.html', context)

accounts/templates/accounts/shared/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Agro</title>
<meta name="viewport" content="width=device-width, initial-scale=1">	
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<meta name="keywords" content="Bootstrap Responsive Templates, Iphone Compatible Templates, Smartphone Compatible Templates, Ipad Compatible Templates, Flat Responsive Templates"/>
<script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Arimo:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script>
    $(function () {
        $('.datetime-input').datetimepicker({
            format:'YYYY-MM-DD'
        });
    });
</script>
	<style>

		.errorlist li{
			color:red;

		}

	</style>
</head>
<body>
	<!--start-header-->
			<div id="home" class="header">
					<div class="top-header">
						<div class="container">
							<div class="logo">
								<a href="#"><img src="{% static 'images/logo.png' %}" height="100" alt=""></a>
							</div>
							<!--start-top-nav-->
							 <!--<div class="top-nav">-->
								<!--<ul>-->
									<!--<li class="active"><a class="play-icon popup-with-zoom-anim" href="#small-dialog"><span> </span>Log in</a></li>-->
									<!--<li><a class="play-icon popup-with-zoom-anim" href="#small-dialog1">Sign up</a></li>-->
								<!--</ul>-->
							<!--</div>-->
							<div class="clearfix"> </div>
						</div>
				</div>
			<!---pop-up-box---->
					  <script type="text/javascript" src="{% static 'js/modernizr.custom.min.js' %}"></script>
					<link href="{% static 'css/popup-box.css' %}" rel="stylesheet" type="text/css" media="all"/>
					<script src="{% static 'js/jquery.magnific-popup.js' %}" type="text/javascript"></script>
					<!---//pop-up-box---->
				<div id="small-dialog" class="mfp-hide">
						<div class="login">
							<h3>Log In</h3>
							<h4>Already a Member</h4>
							<input type="text" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" />
							<input type="password" value="Password" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Password';}"/>
							<input type="submit" value="Login" />
						</div>
					</div>
					<div id="small-dialog1" class="mfp-hide">
						<div class="signup">
							<h3>Sign Up</h3>
							<h4>Enter Your Details Here</h4>
							<input type="text" value="First Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'First Name';}" />
							<input type="text" value="Second Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Second Name';}" />
							<input type="text" class="email"value="Enter Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter Email';}"  />
							<input type="password" value="Password" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Password';}"/>
							<input type="submit"  value="SignUp"/>
						</div>
					</div>	
				 <script>
						$(document).ready(function() {
						$('.popup-with-zoom-anim').magnificPopup({
							type: 'inline',
							fixedContentPos: false,
							fixedBgPos: true,
							overflowY: 'auto',
							closeBtnInside: true,
							preloader: false,
							midClick: true,
							removalDelay: 300,
							mainClass: 'my-mfp-zoom-in'
						});
																						
						});
				</script>					
		<!--End-header-->
    
		<div class="navgation">
          {% include 'accounts/shared/nav.html' %}
			<div class="clearfix"> </div>
		</div>
		</div>

		<div class="care">
			<div class="container">

				{% if messages %}
					<div class="text-right mt-5">
					{% for message in messages %}
					<span{% if message.tags %} class="alert {{ message.tags }} alert-dismissible fade show" role="alert"{% endif %}>
					<strong>{{ message }}</strong>
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					</span>
					{% endfor %}
					</div>
				{% endif %}

				{% block content %}

				{% endblock content %}
			</div>
		</div>
		<script>
			$(function(){
				$('#id_date').attr('min', new Date().toISOString().split('T')[0]);
			})
		</script>
</body>
</html>

accounts/templates/accounts/shared/nav.html
<nav class="navbar navbar-expand-sm navbar-dark">
    <a class="navbar-brand" href="#">AGRO</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation"></button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts_index' %}">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts_login' %}">Login</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts_user_signup' %}">User Registration</a>
            </li>
        </ul>
    </div>
</nav>